cache: cargo
os:
  - linux
language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt clippy
  - sudo apt-get update
  - sudo apt-get -y install libmpv-dev
script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D clippy::all
  - cargo build --all-targets --all-features
  - cargo test --all-targets --all-features
